using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System.IO;
using Leguar.TotalJSON;
using System;
using PlayFab;
using PlayFab.ClientModels;


public class GameManager : MonoBehaviour
{
    public static GameManager instance;
    public PlayerData playerData;
    public string filePath;
    public GlobalLeaderboard globalLeaderboard;
   
    private void Awake()
    {
        if (instance == null)
        {
            instance = this;
        }
        else
        {
            Destroy(this);
        }
    }


    public void SavePlayerData()
    {
        string serialisedDataString = JSON.Serialize(playerData).CreateString();
        File.WriteAllText(filePath, serialisedDataString);
    }


    public void LoadPlayerData()
    {
        if (!File.Exists(filePath))
        {
            playerData = new PlayerData();
            SavePlayerData();
        }
        string fileContents = File.ReadAllText(filePath);
        playerData = JSON.ParseString(fileContents).Deserialize<PlayerData>();
    }








    void Start()
    {
        LoadPlayerData();
        LoginToPlayFab();
    }


    void LoginToPlayFab()
    {


        LoginWithCustomIDRequest request = new LoginWithCustomIDRequest()
        {
            CreateAccount = true,
            CustomId = playerData.uid,
        };


        PlayFabClientAPI.LoginWithCustomID(request, PlayFabLoginResult, PlayFabLoginError);
    }


    // [Serializable]


    // public class LoginWithCustomIDRequest : PlayFabRequestCommon
    // {
        // / <summary>
        /// Automatically create a PlayFab account if one is not currently linked to this ID.
        // / </summary>
        // public bool? CreateAccount;
        // / <summary>
        /// Custom unique identifier for the user, generated by the title.
        // / </summary>
        // public string CustomId;
        // / <summary>
        /// The optional custom tags associated with the request (e.g. build number, external trace identifiers, etc.).
    // }


//     public class PlayerData
//     {
//         public string uid;
//         public string username;
//         public int bestScore;
//         public string bestScoreDate;
//         public int totalPlayersInGame;
//         public string roomName;
   


//     public PlayerData()
//     {
//         uid = Guid.NewGuid().ToString();
//     }
// }


    void PlayFabLoginResult(LoginResult loginResult)
    {
        Debug.Log("PlayFab - Login succeeded:" + loginResult.ToJson());
    }


    void PlayFabLoginError(PlayFabError loginError)
    {
        Debug.Log("PlayFab - Login Failed:" + loginError.ErrorMessage);
    }




}
